[package]
name = "prage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Rust Samurai <chatgpt@openai.com>"]
description = "ğŸ” Minimal password-based file encryption using rage's internals"
readme = "README.md"
repository = "https://github.com/starmoonsky/prage"

[dependencies]
rage = "0.10.0"
rpassword = "7.4.0"
anyhow = "1.0.98"
